spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}${{ Postgres.DATABASE_URL }}
    username: ${PGUSER}
    password: {PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create